### PR TITLE
Add OpenCV non-free installation steps

### PR DESCRIPTION
**Pull request by efernandez**

### CODE REVIEW

**Comment by efernandez** [comment]
@wegunterjr-Dematic Does this change reflects what you did to solve the issue with OpenCV non-free?

**Comment by efernandez** [comment]
Self-reminder: after merging this, cherry-pick the commit into `indigo-devel` and `jade-devel`.

**Comment by efernandez** [comment]
Merging this, as it addresses part of #14

**Comment by efernandez** [comment]
Cherry-pick'd into `indigo-devel` and `hydro-devel`.

**Comment by wegunterjr-Dematic** [comment]
@efernandez  It looks like it does.

**Pull request merged**
